<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "menu".
 *
 * @property integer $id
 * @property string $photo
 * @property string $name
 * @property integer $qty
 * @property string $prices
 * @property integer $categories_id
 * @property integer $user_id
 *
 * @property \backend\models\Categories $categories
 * @property \backend\models\PrepareMenu[] $prepareMenus
 * @property \backend\models\Sale[] $sales
 * @property string $aliasModel
 */
abstract class Menu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'prices', 'categories_id', 'user_id'], 'required'],
            [['qty', 'categories_id', 'user_id'], 'integer'],
            [['prices'], 'number'],
            [['photo', 'name'], 'string', 'max' => 255],
            [['categories_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Categories::className(), 'targetAttribute' => ['categories_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'photo' => 'Photo',
            'name' => 'Name',
            'qty' => 'Qty',
            'prices' => 'Prices',
            'categories_id' => 'Categories ID',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasOne(\backend\models\Categories::className(), ['id' => 'categories_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrepareMenus()
    {
        return $this->hasMany(\backend\models\PrepareMenu::className(), ['menu_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSales()
    {
        return $this->hasMany(\backend\models\Sale::className(), ['menu_id' => 'id']);
    }




}
