<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "prepare_menu".
 *
 * @property integer $id
 * @property integer $table_id
 * @property integer $menu_id
 * @property integer $qty
 * @property string $price
 * @property string $amount
 * @property string $checkbill
 * @property integer $user_id
 *
 * @property \backend\models\Menu $menu
 * @property \backend\models\Tables $table
 * @property string $aliasModel
 */
abstract class PrepareMenu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'prepare_menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['table_id', 'menu_id', 'qty', 'user_id'], 'integer'],
            [['price', 'amount'], 'number'],
            [['checkbill'], 'string', 'max' => 7],
            [['menu_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Menu::className(), 'targetAttribute' => ['menu_id' => 'id']],
            [['table_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Tables::className(), 'targetAttribute' => ['table_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'table_id' => 'Table ID',
            'menu_id' => 'Menu ID',
            'qty' => 'Qty',
            'price' => 'Price',
            'amount' => 'Amount',
            'checkbill' => 'Checkbill',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(\backend\models\Menu::className(), ['id' => 'menu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTable()
    {
        return $this->hasOne(\backend\models\Tables::className(), ['id' => 'table_id']);
    }




}
