<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "purchase_detail".
 *
 * @property integer $id
 * @property integer $qty
 * @property string $price
 * @property string $amount
 * @property integer $purchase_id
 *
 * @property \backend\models\Purchase $purchase
 * @property string $aliasModel
 */
abstract class PurchaseDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['qty', 'purchase_id'], 'integer'],
            [['price', 'amount'], 'number'],
            [['purchase_id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\Purchase::className(), 'targetAttribute' => ['purchase_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'qty' => 'Qty',
            'price' => 'Price',
            'amount' => 'Amount',
            'purchase_id' => 'Purchase ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchase()
    {
        return $this->hasOne(\backend\models\Purchase::className(), ['id' => 'purchase_id']);
    }




}
