<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "purchase".
 *
 * @property integer $id
 * @property string $date
 * @property integer $menu_id
 * @property integer $qty
 * @property string $price
 * @property string $amount
 * @property integer $user_id
 * @property string $description
 * @property string $aliasModel
 */
abstract class Purchase extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'safe'],
            [['menu_id'], 'required'],
            [['menu_id', 'qty', 'user_id'], 'integer'],
            [['price', 'amount'], 'number'],
            [['description'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Date',
            'menu_id' => 'Menu ID',
            'qty' => 'Qty',
            'price' => 'Price',
            'amount' => 'Amount',
            'user_id' => 'User ID',
            'description' => 'Description',
        ];
    }




}
