<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "tables".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property integer $sheet
 * @property integer $user_id
 *
 * @property \backend\models\PrepareMenu[] $prepareMenus
 * @property \backend\models\Sale[] $sales
 * @property string $aliasModel
 */
abstract class Tables extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tables';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'status', 'sheet', 'user_id'], 'required'],
            [['status', 'sheet', 'user_id'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'status' => 'Status',
            'sheet' => 'Sheet',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrepareMenus()
    {
        return $this->hasMany(\backend\models\PrepareMenu::className(), ['table_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSales()
    {
        return $this->hasMany(\backend\models\Sale::className(), ['table_id' => 'id']);
    }




}
